.\" Man page for sort.c, a program in Lab 4 of CSCI 241
.\" Zac Plett and Ezra Goss - Fall 2017

.TH sort_man 1 "26 October 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B sort_man
\- A man page for sort.c

.SH DESCRIPTION
Sort takes in a series of words and sorts them based on flags input by the user

.SH OPTIONS
.IP "-f"
Flag f indicates folding sort, which will sort the words alphabetically ignoring case.
.IP "-n"
Flag n indicates numeric sort, this will take in a number before the words on each line and sort accordingly based on these values. Any line without a value in front will be given a default value of 0.
.IP "-r"
Flag r reverses the order of the sorted elements.
.IP "-? or -h"
Flags ? and h will display a help message, explaining how to use the program.

.SH AUTHORS
Zac Plett and Ezra Goss (Fall 2017)

.SH BUGS
None!
